spring.application.name=springboot-practice

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_chatbot
spring.datasource.username=postgres
spring.datasource.password=aztec

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true